"""create_core_tables

Revision ID: 429f4aefd657
Revises: 
Create Date: 2026-07-03 17:44:12.748810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '429f4aefd657'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitors')),
    sa.UniqueConstraint('normalized_name', name='uq_competitors_normalized_name')
    )
    op.create_index(op.f('ix_competitors_is_active'), 'competitors', ['is_active'], unique=False)
    op.create_index('ix_competitors_name_ar', 'competitors', ['name_ar'], unique=False)
    op.create_index('ix_competitors_name_en', 'competitors', ['name_en'], unique=False)
    op.create_table('social_authors',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('external_author_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_authors')),
    sa.UniqueConstraint('platform', 'external_author_id', name='uq_social_authors_platform_external_author_id')
    )
    op.create_index(op.f('ix_social_authors_platform'), 'social_authors', ['platform'], unique=False)
    op.create_index('ix_social_authors_platform_username', 'social_authors', ['platform', 'username'], unique=False)
    op.create_index(op.f('ix_social_authors_username'), 'social_authors', ['username'], unique=False)
    op.create_table('topic_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_categories'))
    )
    op.create_index(op.f('ix_topic_categories_is_active'), 'topic_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_topic_categories_slug'), 'topic_categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('competitor_aliases',
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_competitor_aliases_competitor_id_competitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitor_aliases')),
    sa.UniqueConstraint('competitor_id', 'normalized_alias', name='uq_competitor_aliases_competitor_id_normalized_alias')
    )
    op.create_index(op.f('ix_competitor_aliases_competitor_id'), 'competitor_aliases', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_competitor_aliases_is_active'), 'competitor_aliases', ['is_active'], unique=False)
    op.create_index('ix_competitor_aliases_normalized_alias', 'competitor_aliases', ['normalized_alias'], unique=False)
    op.create_table('monitoring_rules',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('normalized_value', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_monitoring_rules_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitoring_rules')),
    sa.UniqueConstraint('platform', 'rule_type', 'target_type', 'normalized_value', name='uq_monitoring_rules_unique_value')
    )
    op.create_index('ix_monitoring_rules_active_platform', 'monitoring_rules', ['is_active', 'platform'], unique=False)
    op.create_index(op.f('ix_monitoring_rules_created_by_user_id'), 'monitoring_rules', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_monitoring_rules_is_active'), 'monitoring_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_monitoring_rules_normalized_value'), 'monitoring_rules', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_monitoring_rules_platform'), 'monitoring_rules', ['platform'], unique=False)
    op.create_index(op.f('ix_monitoring_rules_rule_type'), 'monitoring_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_monitoring_rules_target_type'), 'monitoring_rules', ['target_type'], unique=False)
    op.create_table('collection_jobs',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('monitoring_rule_id', sa.UUID(), nullable=True),
    sa.Column('query_value', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_fetched', sa.Integer(), nullable=False),
    sa.Column('total_inserted', sa.Integer(), nullable=False),
    sa.Column('total_duplicates', sa.Integer(), nullable=False),
    sa.Column('total_errors', sa.Integer(), nullable=False),
    sa.Column('cursor_before', sa.String(length=500), nullable=True),
    sa.Column('cursor_after', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('job_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitoring_rule_id'], ['monitoring_rules.id'], name=op.f('fk_collection_jobs_monitoring_rule_id_monitoring_rules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_jobs'))
    )
    op.create_index(op.f('ix_collection_jobs_finished_at'), 'collection_jobs', ['finished_at'], unique=False)
    op.create_index(op.f('ix_collection_jobs_job_type'), 'collection_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_collection_jobs_monitoring_rule_id'), 'collection_jobs', ['monitoring_rule_id'], unique=False)
    op.create_index(op.f('ix_collection_jobs_platform'), 'collection_jobs', ['platform'], unique=False)
    op.create_index('ix_collection_jobs_platform_started_at', 'collection_jobs', ['platform', 'started_at'], unique=False)
    op.create_index('ix_collection_jobs_platform_status', 'collection_jobs', ['platform', 'status'], unique=False)
    op.create_index(op.f('ix_collection_jobs_query_value'), 'collection_jobs', ['query_value'], unique=False)
    op.create_index('ix_collection_jobs_rule_started_at', 'collection_jobs', ['monitoring_rule_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_collection_jobs_started_at'), 'collection_jobs', ['started_at'], unique=False)
    op.create_index(op.f('ix_collection_jobs_status'), 'collection_jobs', ['status'], unique=False)
    op.create_table('collection_job_logs',
    sa.Column('collection_job_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collection_job_id'], ['collection_jobs.id'], name=op.f('fk_collection_job_logs_collection_job_id_collection_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_job_logs'))
    )
    op.create_index(op.f('ix_collection_job_logs_collection_job_id'), 'collection_job_logs', ['collection_job_id'], unique=False)
    op.create_index(op.f('ix_collection_job_logs_event_type'), 'collection_job_logs', ['event_type'], unique=False)
    op.create_index('ix_collection_job_logs_job_level', 'collection_job_logs', ['collection_job_id', 'level'], unique=False)
    op.create_index('ix_collection_job_logs_job_occurred_at', 'collection_job_logs', ['collection_job_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_collection_job_logs_level'), 'collection_job_logs', ['level'], unique=False)
    op.create_index(op.f('ix_collection_job_logs_occurred_at'), 'collection_job_logs', ['occurred_at'], unique=False)
    op.create_table('social_posts',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('external_post_id', sa.String(length=255), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('collection_job_id', sa.UUID(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('clean_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.String(length=255), nullable=True),
    sa.Column('parent_external_post_id', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('like_count', sa.BigInteger(), nullable=False),
    sa.Column('reply_count', sa.BigInteger(), nullable=False),
    sa.Column('repost_count', sa.BigInteger(), nullable=False),
    sa.Column('quote_count', sa.BigInteger(), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['social_authors.id'], name=op.f('fk_social_posts_author_id_social_authors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collection_job_id'], ['collection_jobs.id'], name=op.f('fk_social_posts_collection_job_id_collection_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_posts')),
    sa.UniqueConstraint('platform', 'external_post_id', name='uq_social_posts_platform_external_post_id')
    )
    op.create_index(op.f('ix_social_posts_author_id'), 'social_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_social_posts_collected_at'), 'social_posts', ['collected_at'], unique=False)
    op.create_index(op.f('ix_social_posts_collection_job_id'), 'social_posts', ['collection_job_id'], unique=False)
    op.create_index(op.f('ix_social_posts_conversation_id'), 'social_posts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_social_posts_language'), 'social_posts', ['language'], unique=False)
    op.create_index('ix_social_posts_language_collected_at', 'social_posts', ['language', 'collected_at'], unique=False)
    op.create_index(op.f('ix_social_posts_parent_external_post_id'), 'social_posts', ['parent_external_post_id'], unique=False)
    op.create_index(op.f('ix_social_posts_platform'), 'social_posts', ['platform'], unique=False)
    op.create_index('ix_social_posts_platform_collected_at', 'social_posts', ['platform', 'collected_at'], unique=False)
    op.create_index('ix_social_posts_platform_published_at', 'social_posts', ['platform', 'published_at'], unique=False)
    op.create_index(op.f('ix_social_posts_published_at'), 'social_posts', ['published_at'], unique=False)
    op.create_table('ai_analysis_results',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sentiment_label', sa.String(length=50), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('is_complaint', sa.Boolean(), nullable=False),
    sa.Column('complaint_confidence', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('pipeline_version', sa.String(length=100), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('analysis_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], name=op.f('fk_ai_analysis_results_post_id_social_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analysis_results'))
    )
    op.create_index(op.f('ix_ai_analysis_results_analyzed_at'), 'ai_analysis_results', ['analyzed_at'], unique=False)
    op.create_index('ix_ai_analysis_results_complaint_current', 'ai_analysis_results', ['is_complaint', 'is_current'], unique=False)
    op.create_index(op.f('ix_ai_analysis_results_is_complaint'), 'ai_analysis_results', ['is_complaint'], unique=False)
    op.create_index(op.f('ix_ai_analysis_results_is_current'), 'ai_analysis_results', ['is_current'], unique=False)
    op.create_index(op.f('ix_ai_analysis_results_pipeline_version'), 'ai_analysis_results', ['pipeline_version'], unique=False)
    op.create_index('ix_ai_analysis_results_post_current', 'ai_analysis_results', ['post_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_ai_analysis_results_post_id'), 'ai_analysis_results', ['post_id'], unique=False)
    op.create_index('ix_ai_analysis_results_sentiment_current', 'ai_analysis_results', ['sentiment_label', 'is_current'], unique=False)
    op.create_index(op.f('ix_ai_analysis_results_sentiment_label'), 'ai_analysis_results', ['sentiment_label'], unique=False)
    op.create_index(op.f('ix_ai_analysis_results_status'), 'ai_analysis_results', ['status'], unique=False)
    op.create_table('post_matches',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('monitoring_rule_id', sa.UUID(), nullable=False),
    sa.Column('matched_value', sa.String(length=500), nullable=False),
    sa.Column('matched_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitoring_rule_id'], ['monitoring_rules.id'], name=op.f('fk_post_matches_monitoring_rule_id_monitoring_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], name=op.f('fk_post_matches_post_id_social_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_matches')),
    sa.UniqueConstraint('post_id', 'monitoring_rule_id', 'matched_value', name='uq_post_matches_post_id_monitoring_rule_id_matched_value')
    )
    op.create_index(op.f('ix_post_matches_monitoring_rule_id'), 'post_matches', ['monitoring_rule_id'], unique=False)
    op.create_index('ix_post_matches_monitoring_rule_id_post_id', 'post_matches', ['monitoring_rule_id', 'post_id'], unique=False)
    op.create_index(op.f('ix_post_matches_post_id'), 'post_matches', ['post_id'], unique=False)
    op.create_table('post_entities',
    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('normalized_value', sa.String(length=500), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['ai_analysis_results.id'], name=op.f('fk_post_entities_analysis_result_id_ai_analysis_results'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_post_entities_competitor_id_competitors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], name=op.f('fk_post_entities_post_id_social_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_entities'))
    )
    op.create_index(op.f('ix_post_entities_analysis_result_id'), 'post_entities', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_post_entities_competitor_id'), 'post_entities', ['competitor_id'], unique=False)
    op.create_index('ix_post_entities_competitor_post', 'post_entities', ['competitor_id', 'post_id'], unique=False)
    op.create_index(op.f('ix_post_entities_entity_type'), 'post_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_post_entities_normalized_value'), 'post_entities', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_post_entities_post_id'), 'post_entities', ['post_id'], unique=False)
    op.create_index('ix_post_entities_post_type', 'post_entities', ['post_id', 'entity_type'], unique=False)
    op.create_index('ix_post_entities_type_normalized', 'post_entities', ['entity_type', 'normalized_value'], unique=False)
    op.create_table('post_topics',
    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['ai_analysis_results.id'], name=op.f('fk_post_topics_analysis_result_id_ai_analysis_results'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], name=op.f('fk_post_topics_post_id_social_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_categories.id'], name=op.f('fk_post_topics_topic_id_topic_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_topics'))
    )
    op.create_index(op.f('ix_post_topics_analysis_result_id'), 'post_topics', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_post_topics_is_primary'), 'post_topics', ['is_primary'], unique=False)
    op.create_index(op.f('ix_post_topics_post_id'), 'post_topics', ['post_id'], unique=False)
    op.create_index('ix_post_topics_post_primary', 'post_topics', ['post_id', 'is_primary'], unique=False)
    op.create_index('ix_post_topics_topic_confidence', 'post_topics', ['topic_id', 'confidence'], unique=False)
    op.create_index(op.f('ix_post_topics_topic_id'), 'post_topics', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_topics_topic_id'), table_name='post_topics')
    op.drop_index('ix_post_topics_topic_confidence', table_name='post_topics')
    op.drop_index('ix_post_topics_post_primary', table_name='post_topics')
    op.drop_index(op.f('ix_post_topics_post_id'), table_name='post_topics')
    op.drop_index(op.f('ix_post_topics_is_primary'), table_name='post_topics')
    op.drop_index(op.f('ix_post_topics_analysis_result_id'), table_name='post_topics')
    op.drop_table('post_topics')
    op.drop_index('ix_post_entities_type_normalized', table_name='post_entities')
    op.drop_index('ix_post_entities_post_type', table_name='post_entities')
    op.drop_index(op.f('ix_post_entities_post_id'), table_name='post_entities')
    op.drop_index(op.f('ix_post_entities_normalized_value'), table_name='post_entities')
    op.drop_index(op.f('ix_post_entities_entity_type'), table_name='post_entities')
    op.drop_index('ix_post_entities_competitor_post', table_name='post_entities')
    op.drop_index(op.f('ix_post_entities_competitor_id'), table_name='post_entities')
    op.drop_index(op.f('ix_post_entities_analysis_result_id'), table_name='post_entities')
    op.drop_table('post_entities')
    op.drop_index(op.f('ix_post_matches_post_id'), table_name='post_matches')
    op.drop_index('ix_post_matches_monitoring_rule_id_post_id', table_name='post_matches')
    op.drop_index(op.f('ix_post_matches_monitoring_rule_id'), table_name='post_matches')
    op.drop_table('post_matches')
    op.drop_index(op.f('ix_ai_analysis_results_status'), table_name='ai_analysis_results')
    op.drop_index(op.f('ix_ai_analysis_results_sentiment_label'), table_name='ai_analysis_results')
    op.drop_index('ix_ai_analysis_results_sentiment_current', table_name='ai_analysis_results')
    op.drop_index(op.f('ix_ai_analysis_results_post_id'), table_name='ai_analysis_results')
    op.drop_index('ix_ai_analysis_results_post_current', table_name='ai_analysis_results')
    op.drop_index(op.f('ix_ai_analysis_results_pipeline_version'), table_name='ai_analysis_results')
    op.drop_index(op.f('ix_ai_analysis_results_is_current'), table_name='ai_analysis_results')
    op.drop_index(op.f('ix_ai_analysis_results_is_complaint'), table_name='ai_analysis_results')
    op.drop_index('ix_ai_analysis_results_complaint_current', table_name='ai_analysis_results')
    op.drop_index(op.f('ix_ai_analysis_results_analyzed_at'), table_name='ai_analysis_results')
    op.drop_table('ai_analysis_results')
    op.drop_index(op.f('ix_social_posts_published_at'), table_name='social_posts')
    op.drop_index('ix_social_posts_platform_published_at', table_name='social_posts')
    op.drop_index('ix_social_posts_platform_collected_at', table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_platform'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_parent_external_post_id'), table_name='social_posts')
    op.drop_index('ix_social_posts_language_collected_at', table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_language'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_conversation_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_collection_job_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_collected_at'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_author_id'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_collection_job_logs_occurred_at'), table_name='collection_job_logs')
    op.drop_index(op.f('ix_collection_job_logs_level'), table_name='collection_job_logs')
    op.drop_index('ix_collection_job_logs_job_occurred_at', table_name='collection_job_logs')
    op.drop_index('ix_collection_job_logs_job_level', table_name='collection_job_logs')
    op.drop_index(op.f('ix_collection_job_logs_event_type'), table_name='collection_job_logs')
    op.drop_index(op.f('ix_collection_job_logs_collection_job_id'), table_name='collection_job_logs')
    op.drop_table('collection_job_logs')
    op.drop_index(op.f('ix_collection_jobs_status'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_started_at'), table_name='collection_jobs')
    op.drop_index('ix_collection_jobs_rule_started_at', table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_query_value'), table_name='collection_jobs')
    op.drop_index('ix_collection_jobs_platform_status', table_name='collection_jobs')
    op.drop_index('ix_collection_jobs_platform_started_at', table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_platform'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_monitoring_rule_id'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_job_type'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_finished_at'), table_name='collection_jobs')
    op.drop_table('collection_jobs')
    op.drop_index(op.f('ix_monitoring_rules_target_type'), table_name='monitoring_rules')
    op.drop_index(op.f('ix_monitoring_rules_rule_type'), table_name='monitoring_rules')
    op.drop_index(op.f('ix_monitoring_rules_platform'), table_name='monitoring_rules')
    op.drop_index(op.f('ix_monitoring_rules_normalized_value'), table_name='monitoring_rules')
    op.drop_index(op.f('ix_monitoring_rules_is_active'), table_name='monitoring_rules')
    op.drop_index(op.f('ix_monitoring_rules_created_by_user_id'), table_name='monitoring_rules')
    op.drop_index('ix_monitoring_rules_active_platform', table_name='monitoring_rules')
    op.drop_table('monitoring_rules')
    op.drop_index('ix_competitor_aliases_normalized_alias', table_name='competitor_aliases')
    op.drop_index(op.f('ix_competitor_aliases_is_active'), table_name='competitor_aliases')
    op.drop_index(op.f('ix_competitor_aliases_competitor_id'), table_name='competitor_aliases')
    op.drop_table('competitor_aliases')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_topic_categories_slug'), table_name='topic_categories')
    op.drop_index(op.f('ix_topic_categories_is_active'), table_name='topic_categories')
    op.drop_table('topic_categories')
    op.drop_index(op.f('ix_social_authors_username'), table_name='social_authors')
    op.drop_index('ix_social_authors_platform_username', table_name='social_authors')
    op.drop_index(op.f('ix_social_authors_platform'), table_name='social_authors')
    op.drop_table('social_authors')
    op.drop_index('ix_competitors_name_en', table_name='competitors')
    op.drop_index('ix_competitors_name_ar', table_name='competitors')
    op.drop_index(op.f('ix_competitors_is_active'), table_name='competitors')
    op.drop_table('competitors')
    # ### end Alembic commands ###
